"""
Converts a validated CleanUniversity dict (snake_case, matches the Python
models) into the exact JSON shape the app's University schema expects
(camelCase field names). id/createdAt/updatedAt are intentionally NOT
included -- those are generated by the database at insert time, not by
the scraper (same reasoning as the omitted latitude/longitude at the
scraper stage, just one step later in the pipeline).
"""


def _program_to_app_schema(program: dict) -> dict:
    return {
        "name": program.get("name"),
        "degreeType": program.get("degree_type"),
        "durationYears": program.get("duration_years"),
        "description": program.get("description"),
    }


def _club_to_app_schema(club: dict) -> dict:
    return {
        "name": club.get("name"),
        "description": club.get("description"),
        "logoUrl": club.get("logo_url"),
        "contactInfo": club.get("contact_info"),
    }


def _event_to_app_schema(event: dict) -> dict:
    return {
        "title": event.get("title"),
        "description": event.get("description"),
        "startDate": event.get("start_date"),
        "endDate": event.get("end_date"),
    }


def _location_to_app_schema(location: dict | None) -> dict | None:
    if not location:
        return None
    return {
        "address": location.get("address"),
        "city": location.get("city"),
        "latitude": location.get("latitude"),
        "longitude": location.get("longitude"),
        # "address" | "institution" | "city" | None -- lets the app tell a
        # rooftop match from a city centroid instead of dropping every pin
        # as if it were equally precise.
        "geocodePrecision": location.get("geocode_precision"),
    }


def to_app_schema(uni: dict) -> dict:
    """University + nested Location/Program/Club/Event/Tag, camelCase,
    matching the app's schema exactly. No id/createdAt/updatedAt -- the
    database generates those on insert."""
    return {
        "name": uni.get("name"),
        # Short forms / acronyms ("ENIS", "INSAT") the site itself uses.
        # The spec's keyword search needs these: users type the acronym.
        "aliases": uni.get("aliases", []),
        "type": uni.get("type"),
        "description": uni.get("description"),
        "logoUrl": uni.get("logo_url"),
        "coverImageUrl": uni.get("cover_image_url"),
        "website": uni.get("website"),
        "email": uni.get("email"),
        "phone": uni.get("phone"),
        "location": _location_to_app_schema(uni.get("location")),
        "programs": [_program_to_app_schema(p) for p in uni.get("programs", [])],
        "clubs": [_club_to_app_schema(c) for c in uni.get("clubs", [])],
        "events": [_event_to_app_schema(e) for e in uni.get("events", [])],
        "tags": uni.get("tags", []),
    }
